# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan Dzoan
email: dandzoan@gmail.com
description: Software Engineer, Traveler, Former World Record Holder
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dandzoan.com" # the base hostname & protocol for your site
github_username:  ddzoan

# Build settings
markdown: kramdown
